server:
  port: 8181
mail:
  cache-templates: false # Cache templates as local files
  from: 'no-reply@example.com' # Sender E-Mail Address
  from-password: 'email-account-password' # Sender E-Mail Passwor
  smtp-host: 'mail.example.com' # Mailserver Host
  smtp-port: '587' # Mailserver Port
database:
  use: 'inmemory' # [inmemory, mysql]
  mysql:
    username: 'db-user-username'
    password: 'db-user-password'
    database: 'tcp(localhost:3306)/db-name'
    parameters:
      - 'charset=utf8mb4'
      - 'collation=utf8mb4_general_ci'
      - 'parseTime=True'
      - 'timeout=30s' # connection timeout
security:
  disable_cors: false
