server:
  port: 9093
mail:
  log_only: false # Only log the E-Mail (Requires logging to be set to DEBUG). No sending.
  dev_mode: false # Override the recipient (To) to the list below, ignore Bcc/Cc.
  dev_mails:
    - 'developer@example.com'
    - 'another.dev@example.com'
  # optional debug option that adds this mail address to Bcc on every email sent
  # add_auto_bcc: 'debug@example.com'
  from: 'Example Sender <no-reply@example.com>' # Sender E-Mail Address (Can be either just "email@example.com" OR "Example <email@example.com>"
  from_password: 'email-account-password' # Sender E-Mail Password
  smtp_host: 'mail.example.com' # Mail-server Host
  smtp_port: '587' # Mail-server Port
database:
  use: 'inmemory' # [inmemory, mysql]
  username: 'db-user-username'
  password: 'db-user-password'
  database: 'tcp(localhost:3306)/db-name'
  parameters:
    - 'charset=utf8mb4'
    - 'collation=utf8mb4_general_ci'
    - 'parseTime=True'
    - 'timeout=30s' # connection timeout
security:
  fixed_token:
    api: 'put_secure_random_string_here_for_api_token'
  oidc:
    # set this nonempty to read the jwt token from a cookie
    id_token_cookie_name: 'JWT'
    access_token_cookie_name: 'AUTH'
    # a list of public RSA keys in PEM format, see https://github.com/Jumpy-Squirrel/jwks2pem for obtaining PEM from openid keyset endpoint
    token_public_keys_PEM:
      - |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
        vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
        aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
        tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
        e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
        V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
        MwIDAQAB
        -----END PUBLIC KEY-----
    admin_group: 'admin'
    # if you leave this blank, userinfo checks will be skipped
    auth_service: 'http://localhost:4712' # no trailing slash
    # optional, but will be checked if set (should set to reject tokens created for other clients than regsys)
    audience: 'only-allowed-audience-in-tokens'
    # optional, but will be checked if set
    issuer: 'only-allowed-issuer-in-tokens'
  cors:
    # set this to true to send disable cors headers - not for production - local/test instances only - will log lots of warnings
    disable: false
    # if setting disable_cors, you should also specify this, as a comma separated list of allowed origins
    allow_origin: 'http://localhost:8000'
logging:
  severity: INFO
  style: plain # or ecs (elastic common schema), the default
